SET IDENTITY_INSERT SnapConnect.dbo.proposals ON

INSERT INTO [SnapConnect].[dbo].[proposals]
	   ([id]
      ,[create_date]
      ,[expire_date]
      ,[subscriber]
      ,[terms]
      ,[discount]
      ,[fees]
      ,[sales_agent]
      ,[telapex_company]
      ,[recurring_total]
      ,[total]
      ,[commissions]
      ,[accepted_date]
      ,[notes]
      ,[inside_city]
      ,[tax_exempt]
      ,[tax_id]
      ,[payment_terms]
      ,[access_fee]
      ,[status])
      
SELECT [id]
      ,[createDate]
      ,[expireDate]
      ,[subscriber]
      ,[terms]
      ,[discount]
      ,[fees]
      ,[salesperson]
      ,[tpxCompany]
      ,[recurringTotal]
      ,[total]
      ,[commissions]
      ,[accepteddate]
      ,[notes]
      ,[insidecity]
      ,[taxexempt]
      ,[taxid]
      ,[paymentterms]
      ,[accessfee]
      ,[status]
  FROM [TPISQL].[Utilities].[dbo].[TPX_Security_Proposals]
GO


